[package]
name = "eric-bindings"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
build = "build.rs"

[lib]
path = "src/lib.rs"
name = "eric_bindings"

[dependencies]
anyhow = { workspace = true }

[build-dependencies]
bindgen = "0.69.4"
