[package]
name = "eric-sdk"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
readme.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Rust SDK for the ELSTER Rich Client (ERiC)"
keywords = ["eric", "sdk",  "taxes", "accounting"]
categories = ["finance"]

[lib]
path = "src/lib.rs"
name = "eric_sdk"

[dependencies]
eric-bindings = { version = "0.1.2", path = "../eric-bindings" }
anyhow = { workspace = true }

[dev-dependencies]
