name: CI
on:
  push:
    branches: [main]
  pull_request:
env:
  CARGO_TERM_COLOR: always
  LIBRARY_NAME: ericapi
  LIBRARY_PATH: ERiC-39.6.4.0-Linux-x86_64/ERiC-39.6.4.0/Linux-x86_64/lib
  HEADER_FILE: ERiC-39.6.4.0-Linux-x86_64/ERiC-39.6.4.0/Linux-x86_64/include/ericapi.h
  PLUGIN_PATH: ERiC-39.6.4.0-Linux-x86_64/ERiC-39.6.4.0/Linux-x86_64/lib/plugins2
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: cargo check
        run: cargo check --all-targets
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: cargo clippy -- -D warnings
        run: cargo clippy --all-targets -- -D warnings
  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: cargo doc
        run: cargo doc --no-deps
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: cargo fmt --check
        run: cargo fmt --check
  fmt-nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - name: cargo +nightly fmt --check
        run: cargo +nightly fmt --check
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: dtolnay/rust-toolchain@stable
  #     - name: cargo test --lib
  #       run: cargo test --lib -p eric-sdk
  doc-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: cargo test --doc
        run: cargo test --locked --doc -p eric-sdk
